// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma supports `directUrl`, but the config types may lag.
  // Casting avoids Next.js typecheck failures.
  datasource: ({
    url: process.env["DATABASE_URL"],
    directUrl: process.env["DIRECT_URL"],
  } as unknown as { url?: string; directUrl?: string }),
});
